### PR TITLE
create a sql schema

### PR DESCRIPTION
**Pull request by chandracanth5495**
The sql schema contains the decided things in MySQL format.

### CODE REVIEW

**Comment by chandracanth5495** [comment]
@chhanganivarun Please see the new PR

**Comment by chhanganivarun** [comment]
@chandracanth5495 please find the format of authentication yourself once and then let's talk.

**Comment by chhanganivarun** [comment]
Why is the time there in authentication token table?

**Comment by chandracanth5495** [comment]
> Why is the time there in authentication token table?

to note the expiry of the token

**Review by chhanganivarun — CHANGES_REQUESTED** [review]
please also add a userAgent entry in the table authenticate (varcha(511)) and place authenticate table just below pass for easy visibility

**Review by chhanganivarun — APPROVED** [review]

**Comment by chhanganivarun** [comment]
@catchmoosa please check if all is fine

**Review by catchmoosa — APPROVED** [review]

**Pull request merged**
